services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - "9092:9092"
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      retries: 10


  identity-db:
    image: postgres:15
    environment:
      POSTGRES_DB: identitydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MinhaSenha123
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 10
    volumes:
      - identity-db-data:/var/lib/postgresql/data


  catalog-db:
    image: postgres:15
    environment:
      POSTGRES_DB: catalogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MinhaSenha123
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 10
    volumes:
      - catalog-db-data:/var/lib/postgresql/data


  orders-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MinhaSenha123
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 10
    volumes:
      - orders-db-data:/var/lib/postgresql/data
    
  
  identity:
    build:
      context: .
      dockerfile: Identity.API/Dockerfile
    ports:
      - "5070:8080"
    depends_on:
      - identity-db
    environment:
      - ConnectionStrings__DefaultConnection=Host=identity-db;Port=5432;Database=identitydb;Username=postgres;Password=MinhaSenha123
      
  catalog:
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy  
      catalog-db:
        condition: service_healthy
    environment:
      - Kafka__BootstrapServers=kafka:9092
      - ConnectionStrings__DefaultConnection=Host=catalog-db;Port=5432;Database=catalogdb;Username=postgres;Password=MinhaSenha123
    ports:
      - "5066:8080"
    
  orders:
    build:
      context: .
      dockerfile: Orders.API/Dockerfile
    depends_on:
      - kafka
      - catalog
      - orders-db
    environment:
      - Kafka__BootstrapServers=kafka:9092
      - ConnectionStrings__DefaultConnection=Host=orders-db;Port=5432;Database=ordersdb;Username=postgres;Password=MinhaSenha123
    ports:
      - "5045:8080"


volumes:
  identity-db-data:
  catalog-db-data:
  orders-db-data: